### ISSUE TITLE
Enhancement: Include OTP codes in migration, migrate passwords alot faster

### ISSUE THREAD

**Issue by Luke-Williams9** [lwhitelock/ITGlue-Hudu-Migration#17]
I've added OTP secret migration in my fork of this script. Since there is already a full IT Glue export required for the script, its easy / much faster to pull the passwords + OTP codes from the passwords.csv instead of querying each IT Glue password from the API one by one.

https://github.com/Luke-Williams9/ITGlue-Hudu-Migration/commit/3042fe5e67777f1fdf8df2fd07652d5a71e40456

**Comment by greenlighttec** [comment]
This is already handled in the 2024-dev version of the script
