### ISSUE TITLE
List passwords with OTP secrets in the manual actions file

### ISSUE THREAD

**Issue by mtcjoshua** [lwhitelock/ITGlue-Hudu-Migration#6]
One of the things that ITGlue doesn't export is the OTP secrets, so those will have to be manually added to Hudu (either via knowing the secret outside of ITG, or resetting those).  It would be nice if the manualactions.html file included all of the passwords that had OTP set up.

I'm not sure how easy it would be to track those when importing the passwords, I just ran a quick script afterwards to list them out using the csv files in the ITG export.

```
$export_dir = "c:\temp\itglue\export\"
$itg_url = "<ITG URL>"
$org_list = (import-csv "$($export_dir)organizations.csv")
$otp_list = (import-csv "$($export_dir)passwords.csv" | where-object {$_.one_time_password -eq "Yes"})
foreach ($otp in $otp_list) {
	$org = ($org_list | where-object {$_.name -eq "$($otp.organization)"}).id
	Write-Host "$($itg_url)/$($org)/passwords/$($otp.id)"
}
```

**Comment by greenlighttec** [comment]
OTP is now included in the ITGlue export and has been added to the new versino of the script.

**Comment by akraker99** [comment]
What would be the process for getting the OTP's merged into previously imported passwords using the official script?  We exported ITGlue with OTP's and ran the migration script that does not import the OTP's already.  Other than the missing OTP's, everything went great.
I tried running the newer script and chose not to import anything but the passwords and it did import the OTP's but they are duplicated passwords and are not matched with any related items.

**Comment by greenlighttec** [comment]
@akraker99 you would need to still have the MigrationLogs folder that was created upon first running the import, the one the script tells you to never delete 😉

Inside that folder you'll have a passwords.json and another one for asset passwords assetpasswords.json maybe?

The steps would be as follows.

1. `Get-Content` for the two files, convertfrom-json for that content to get them into variabes. (Maybe `$JSONPasswords` and `$JSONAssetPasswords`).
2. `$CSVPasswords = import-csv -path /path/to/new/passwords.csv` that has the TOTP Seeds
3. Loop on CSV Passwords, and inside the foreach obtain the HuduID by using `$HuduID = ($JSONPasswords | Where-Object {$_.itgid -eq $Password.id}).HuduID` You'll want to do this for both JSONPasswords and JSONAssetPasswords in case the password is in one or the other.
4. `Set-HuduPassword -id $HuduID -OTPSecret $Password.otp_secret` inside the foreach once you confirm $HuduID exists. This will update the password with the new seed. **Make sure you're on the latest version of the HuduAPI module that just came out**

This is all from memory so validate everything first, and please test your foreach on a single password before all of them. Also standard disclaimer applies, I'm not responsible for anything that happens on your system, I'm assuming a basic knowledge of powershell for these instructions and so on.

If you don't have the log files anymore, you'll need to match by username, password, and any other data point that can give you a gauranteed match between the passwords.csv and the password in Hudu.

**Comment by OrbitsIT** [comment]
Where can we find the latest script please?
