### ISSUE TITLE
Embedded KBA URLs not getting updated correctly

### ISSUE THREAD

**Issue by jspern** [lwhitelock/ITGlue-Hudu-Migration#8]
Not sure if this had anything to do with our specific configuration or a mistake we made during the migration setup, but all of the docs that were migrated that had URLs to other docs embedded in them had their URLs updated, but not quite correctly:

![image](https://user-images.githubusercontent.com/41965203/190012909-7e443ff5-ee06-485e-9ef7-4d0c013ffe98.png)

Expectation: Embedded URLs are updated with the correct Hudu URL, e.g. `https://docs.hudu.com/kba/article1`
Actuality: Embedded URLs have duplicate text, e.g. `https://docs.hudu.comhttp://docs.hudu.com/kba/article1`

**Comment by greenlighttec** [comment]
this should be fixed in the new version of the script
